# Run short and medium tests (as defined in test frameworks), equivalent to 'make check'.
#
# This workflow is run on 'self-hosted' runners.
name: PMEM check

on: 
  workflow_dispatch:
  schedule:
    # run this job every 8 hours
    - cron:  '0 */8 * * *'

jobs:
  linux:
    name: PMEM_check
    if: github.repository == 'pmem/pmdk'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, rhel],[self-hosted, opensuse]]
        config: ['debug', 'nondebug', 'static_debug', 'static_nondebug']
    env:
      WORKDIR: utils/gha-runners

    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Get system information
        run: ./$WORKDIR/get-system-info.sh

      - name: Build
        run: ./$WORKDIR/build-pmdk.sh

      - name: Create testconfig files
        run: ./$WORKDIR/create-testconfig.sh

      - name: Run tests check
        run: make check TEST_BUILD=${{ matrix.config }}

      - name: Run tests pycheck
        run: make pycheck TEST_BUILD=${{ matrix.config }}
